import dotenv from "dotenv";
import mongoose from "mongoose";
import colors from "colors";
import Register from "./models/Register.js";

// Load environment variables
dotenv.config();

const setupAdmin = async () => {
  try {
    // Connect to MongoDB
    console.log("Connecting to MongoDB...".yellow);
    await mongoose.connect(process.env.MONGO_URI);
    console.log(`MongoDB Connected: ${mongoose.connection.host}`.bgCyan.white);

    // Admin user details
    const adminEmail = "ramooz5hajj@gmail.com";
    const adminPassword = "123456";

    // Demo user details
    const demoEmail = "demo@crmportaltravel.com";
    const demoPassword = "demo123";

    let adminCreated = false;
    let demoCreated = false;

    // Check if admin already exists
    const existingAdmin = await Register.findOne({ email: adminEmail });

    if (existingAdmin) {
      console.log("Admin user already exists!".bgYellow.black);
    } else {
      // Create new admin user
      console.log("Creating admin user...".yellow);

      await Register.create({
        name: "CRM Portal Ticket Travel Admin",
        email: adminEmail,
        phone: "03014554747",
        password: adminPassword,
        plainPassword: adminPassword,
        isAutoGeneratedPassword: false,
        role: "Admin",
        status: "Active",
        address: "Faisalabad",
        country: "Pakistan",
        city: "Faisalabad",
        companyName: "CRM Portal Ticket Travel",
        consultant: "",
      });

      console.log("✓ Admin user created successfully!".bgGreen.white);
      adminCreated = true;
    }

    // Check if demo user already exists
    const existingDemo = await Register.findOne({ email: demoEmail });

    if (existingDemo) {
      console.log("Demo user already exists!".bgYellow.black);
    } else {
      // Create demo user
      console.log("Creating demo user...".yellow);

      await Register.create({
        name: "Demo User",
        email: demoEmail,
        phone: "03014554747",
        password: demoPassword,
        plainPassword: demoPassword,
        isAutoGeneratedPassword: false,
        role: "User",
        status: "Active",
        address: "Demo Address",
        country: "Pakistan",
        city: "Demo City",
      });

      console.log("✓ Demo user created successfully!".bgGreen.white);
      demoCreated = true;
    }

    // Display all credentials
    if (adminCreated || demoCreated) {
      console.log("\n" + "=".repeat(50).green);
      console.log("Setup Complete! User Credentials:".cyan.bold);
      console.log("=".repeat(50).green);

      if (adminCreated) {
        console.log("\nAdmin User:".cyan.bold);
        console.log(`  Email: ${adminEmail}`.cyan);
        console.log(`  Password: ${adminPassword}`.cyan);
      }

      if (demoCreated) {
        console.log("\nDemo User:".cyan.bold);
        console.log(`  Email: ${demoEmail}`.cyan);
        console.log(`  Password: ${demoPassword}`.cyan);
      }

      console.log("\n" + "=".repeat(50).green);
    } else {
      console.log(
        "\nAll users already exist. No new users created.".bgYellow.black,
      );
    }

    process.exit(0);
  } catch (error) {
    console.error("Error during setup:".bgRed.white);
    console.error(error.message.red);
    process.exit(1);
  }
};

// Run setup
setupAdmin();
